### ISSUE TITLE
Implementar função de Divisão

### ISSUE THREAD

**Issue by FlightofIcarus** [FlightofIcarus/CODElivery#11]

**Comment by jcpds14** [comment]
Esta função chamada divide calcula a divisão de number1 por number2. Antes de realizar a divisão, ela verifica se number2 é igual a zero para evitar uma divisão por zero, retornando uma mensagem de erro nesse caso. Caso number2 seja diferente de zero, a função retorna o resultado da divisão de number1 por number2. Pode-se utilizar esta função importando-a como um módulo.
