### ISSUE TITLE
Implementar função de Raiz Quadrada

### ISSUE THREAD

**Issue by FlightofIcarus** [FlightofIcarus/CODElivery#13]

**Comment by jcpds14** [comment]
Essa função chamada squareRoot calcula a raiz quadrada de um número. Ela aceita um único argumento, number, que representa o número do qual você deseja calcular a raiz quadrada.
A função utiliza o método Math.sqrt() para realizar o cálculo da raiz quadrada do number e, em seguida, retorna o resultado.
Pode ser utilizada importando como módulo.
