### ISSUE TITLE
Implementar função de Percentual

### ISSUE THREAD

**Issue by FlightofIcarus** [FlightofIcarus/CODElivery#14]

**Comment by jcpds14** [comment]
Essa função chamada percentage calcula o valor percentual de um número em relação a um determinado percentual. Ela pega dois argumentos: number, que é o número ao qual você deseja calcular o percentual, e percent, que é o percentual desejado.
A função divide number por 100 para obter a representação decimal do percentual e, em seguida, multiplica esse valor pelo percent. O resultado é o valor percentual desejado. 
Pode ser utilizada importando um módulo.
